version: "3.2"

services:
  node:
    build:
      context: .
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - mongo
    labels:
        kompose.service.type: "loadbalancer"
        kompose.service.expose: "true"
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
