version: "3.2"

services:
  node:
    build:
      context: .
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
  nginx:
    build: ./docker/nginx/
    depends_on:
      - node
    ports:
      - "80:80"
      - "443:443"
    restart: always
    labels:
        kompose.service.type: "loadbalancer"
        kompose.service.expose: "true"
