version: "3.2"

services:
  node:
    image: smilebhai/node:latest
    volumes:
    # https://stackoverflow.com/a/32785014/232619
      - .:/app
      - /app/node_modules
    command: /usr/local/wait-for-it.sh mongo:27017 -- npm start
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - mongo
    labels:
        kompose.service.type: "loadbalancer"
        kompose.service.expose: "true"
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
