version: "3.2"

services:
  nginx:
    image: smilebhai/nginx:latest
    depends_on:
      - node
    ports:
      - "80:80"
      - "443:443"
    restart: always
    labels:
      kompose.service.type: "loadbalancer"
      kompose.service.expose: "true"
